name: Build and Attach .unitypackage

on:
  release:
    types: [created]

jobs:

  build-and-upload-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Build Package'
        uses: ncipollo/unity-action@master
        with: 
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          serial: ${{ secrets.serial }}
          license: ${{ secrets.license }}
          mode: build
          build_method: ExportPackage.Run

      - name: Upload Package
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "RadarUnitySDK.unitypackage"
          asset_name: "RadarUnitySDK.unitypackage"
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}